# Generated by Django 4.1.1 on 2022-09-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='접속시간')),
                ('location', models.CharField(max_length=50, verbose_name='접속 경로')),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
