# Generated by Django 4.1.1 on 2022-09-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0002_accesslog_delete_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='접속시간'),
        ),
    ]
